apiVersion: v1
kind: PersistentVolume
metadata:
  name: gke-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: ext4
