apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gke-filestore-pvc
  namespace: new7
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti  # Match the size with the PV
  selector:
    matchLabels:
      app: system-monitoring-app

